use_frameworks!

platform :ios, '10.0'

target 'MYDearUpload_Example' do
  pod 'MYDearUpload', :path => '../'

  target 'MYDearUpload_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
